package treedbstats

import "testing"

func TestSelectedKeepsSharedTreeDBStats(t *testing.T) {
	stats := map[string]string{
		"treedb.commit_seq":          "7",
		"treedb.applied_command_lsn": "9",
		"treedb.command_wal.enabled": "true",
		"treedb.command_wal.frames":  "3",
		"treedb.process.read_path.backend_tree.get_append_pointer_hits_total":              "5",
		"treedb.process.read_path.outer_leaf.cache.hits":                                   "11",
		"treedb.vlog.mmap_read.fallback_readat":                                            "13",
		"treedb.vlog.mmap_max_mapped_leaf_sealed_bytes":                                    "8589934592",
		"treedb.vlog.grouped_frame_cache.retained_bytes":                                   "67108864",
		"treedb.process.memory.rss_bytes":                                                  "123456789",
		"treedb.cache.vlog_mmap.max_mapped_leaf_sealed_segments":                           "512",
		"treedb.cache.vlog_auto.frames.block_lz4":                                          "37",
		"treedb.cache.vlog_auto.frames.block_zstd":                                         "17",
		"treedb.cache.vlog_write_mode.stored_ratio.block":                                  "0.500000",
		"treedb.cache.vlog_payload_kind.frames.outer_leaf":                                 "41",
		"treedb.cache.vlog_payload_split.records.outer_leaf":                               "83",
		"treedb.cache.vlog_outer_leaf_codec.frames.lz4":                                    "43",
		"treedb.cache.vlog_block.k.bucket.lz4.le_1":                                        "43",
		"treedb.cache.vlog_dict.frames_kept":                                               "2",
		"treedb.cache.vlog_autotune.observed_ratio":                                        "0.410000",
		"treedb.cache.vlog_leaf_scan.write_mode.frames.block":                              "5",
		"treedb.cache.flush_apply.planning_ns_total":                                       "101",
		"treedb.cache.flush_span_run.source_point_ops_total":                               "11",
		"treedb.cache.flush_span_run.planned_point_ops_total":                              "10",
		"treedb.cache.flush_span_run.backend_chunks_total":                                 "4",
		"treedb.cache.checkpoint.total_ms":                                                 "1.250",
		"treedb.cache.checkpoint.cutover_last_ms":                                          "0.500",
		"treedb.cache.checkpoint.stage.flush_all.total_ns":                                 "303",
		"treedb.flush_apply.old_leaf_read_decode.leaf_log_node_loads_total":                "7",
		"treedb.flush_apply.read_only_prepare.spans_total":                                 "3",
		"treedb.flush_apply.leaf_log_output.append_wait_ns_total":                          "1234",
		"treedb.flush_apply.span_native.scheduler.worker_busy_ns_total":                    "7000",
		"treedb.flush_apply.span_native.scheduler.worker_idle_ns_total":                    "3000",
		"treedb.flush_apply.span_native.scheduler.ready_tasks_total":                       "8",
		"treedb.flush_apply.span_native.scheduler.task_spans_per_task":                     "6.000000",
		"treedb.flush_apply.publish_prepare.ns_total":                                      "44",
		"treedb.flush_apply.publish_final_install.ns_total":                                "55",
		"treedb.flush_apply.publish_total.ns_total":                                        "99",
		"treedb.flush_apply.reducer_publish.ns_total":                                      "99",
		"treedb.publish.ordered_root_delta_group.calls_total":                              "19",
		"treedb.publish.ordered_root_delta_group.publish_prepare_ns_total":                 "66",
		"treedb.publish.ordered_root_delta_group.root_apply_read_only_prepare_spans_total": "2",
		"treedb.publish.watermark.latency_p99_ms":                                          "23",
		"treedb.collections.write_domain.indexed_flush.calls_total":                        "29",
		"treedb.unrelated_stat_that_should_not_leave_the_helper":                           "17",
	}
	got := Selected(stats)
	for _, key := range []string{
		"treedb.commit_seq",
		"treedb.applied_command_lsn",
		"treedb.command_wal.enabled",
		"treedb.command_wal.frames",
		"treedb.process.read_path.backend_tree.get_append_pointer_hits_total",
		"treedb.process.read_path.outer_leaf.cache.hits",
		"treedb.vlog.mmap_read.fallback_readat",
		"treedb.vlog.mmap_max_mapped_leaf_sealed_bytes",
		"treedb.vlog.grouped_frame_cache.retained_bytes",
		"treedb.process.memory.rss_bytes",
		"treedb.cache.vlog_mmap.max_mapped_leaf_sealed_segments",
		"treedb.cache.vlog_auto.frames.block_lz4",
		"treedb.cache.vlog_auto.frames.block_zstd",
		"treedb.cache.vlog_write_mode.stored_ratio.block",
		"treedb.cache.vlog_payload_kind.frames.outer_leaf",
		"treedb.cache.vlog_payload_split.records.outer_leaf",
		"treedb.cache.vlog_outer_leaf_codec.frames.lz4",
		"treedb.cache.vlog_block.k.bucket.lz4.le_1",
		"treedb.cache.vlog_dict.frames_kept",
		"treedb.cache.vlog_autotune.observed_ratio",
		"treedb.cache.vlog_leaf_scan.write_mode.frames.block",
		"treedb.cache.flush_apply.planning_ns_total",
		"treedb.cache.flush_span_run.source_point_ops_total",
		"treedb.cache.flush_span_run.planned_point_ops_total",
		"treedb.cache.flush_span_run.backend_chunks_total",
		"treedb.cache.checkpoint.total_ms",
		"treedb.cache.checkpoint.cutover_last_ms",
		"treedb.cache.checkpoint.stage.flush_all.total_ns",
		"treedb.flush_apply.old_leaf_read_decode.leaf_log_node_loads_total",
		"treedb.flush_apply.read_only_prepare.spans_total",
		"treedb.flush_apply.leaf_log_output.append_wait_ns_total",
		"treedb.flush_apply.span_native.scheduler.worker_busy_ns_total",
		"treedb.flush_apply.span_native.scheduler.worker_idle_ns_total",
		"treedb.flush_apply.span_native.scheduler.ready_tasks_total",
		"treedb.flush_apply.span_native.scheduler.task_spans_per_task",
		"treedb.flush_apply.publish_prepare.ns_total",
		"treedb.flush_apply.publish_final_install.ns_total",
		"treedb.flush_apply.publish_total.ns_total",
		"treedb.flush_apply.reducer_publish.ns_total",
		"treedb.publish.ordered_root_delta_group.calls_total",
		"treedb.publish.ordered_root_delta_group.publish_prepare_ns_total",
		"treedb.publish.ordered_root_delta_group.root_apply_read_only_prepare_spans_total",
		"treedb.publish.watermark.latency_p99_ms",
		"treedb.collections.write_domain.indexed_flush.calls_total",
	} {
		if got[key] == "" {
			t.Fatalf("Selected missing %s from %#v", key, got)
		}
	}
	if _, ok := got["treedb.unrelated_stat_that_should_not_leave_the_helper"]; ok {
		t.Fatalf("Selected kept unrelated stat: %#v", got)
	}
}
