package treedbstats

import "testing"

func TestSelectedKeepsSharedTreeDBStats(t *testing.T) {
	stats := map[string]string{
		"treedb.commit_seq":          "7",
		"treedb.applied_command_lsn": "9",
		"treedb.command_wal.enabled": "true",
		"treedb.command_wal.frames":  "3",
		"treedb.process.read_path.backend_tree.get_append_pointer_hits_total":                           "5",
		"treedb.process.read_path.outer_leaf.cache.hits":                                                "11",
		"treedb.vlog.mmap_read.fallback_readat":                                                         "13",
		"treedb.vlog.mmap_max_mapped_leaf_sealed_bytes":                                                 "2147483648",
		"treedb.vlog.decode_buffer_grow.read_append_decoded_payload.calls_total":                        "7",
		"treedb.vlog.decode_scratch.small_pool.retained_bytes":                                          "32768",
		"treedb.vlog.writer_append_buf.pool.retained_bytes":                                             "4194304",
		"treedb.vlog.grouped_frame_cache.retained_bytes":                                                "67108864",
		"treedb.vlog.grouped_frame_cache.allocated_slots":                                               "512",
		"treedb.cache.vlog_grouped_frame_cache.retained_bytes":                                          "33554432",
		"treedb.cache.vlog_grouped_frame_cache.allocated_slots":                                         "256",
		"treedb.process.memory.rss_bytes":                                                               "123456789",
		"treedb.cache.vlog_mmap.max_mapped_leaf_sealed_segments":                                        "512",
		"treedb.cache.vlog_decode_buffer_grow.read_append_decoded_payload.calls_total":                  "17",
		"treedb.cache.vlog_decode_scratch.small_pool.retained_bytes":                                    "65536",
		"treedb.cache.vlog_writer_append_buf.pool.retained_bytes":                                       "8388608",
		"treedb.cache.vlog_auto.frames.block_lz4":                                                       "37",
		"treedb.cache.vlog_auto.frames.block_zstd":                                                      "17",
		"treedb.cache.vlog_write_mode.stored_ratio.block":                                               "0.500000",
		"treedb.cache.vlog_payload_kind.frames.outer_leaf":                                              "41",
		"treedb.cache.vlog_payload_split.records.outer_leaf":                                            "83",
		"treedb.cache.vlog_outer_leaf_codec.frames.lz4":                                                 "43",
		"treedb.cache.vlog_block.k.bucket.lz4.le_1":                                                     "43",
		"treedb.cache.vlog_dict.frames_kept":                                                            "2",
		"treedb.cache.vlog_autotune.observed_ratio":                                                     "0.410000",
		"treedb.cache.vlog_leaf_scan.write_mode.frames.block":                                           "5",
		"treedb.cache.memtable_residency.queue.append_only.entry_backing_bytes":                         "7340032",
		"treedb.cache.memtable_residency.queue.append_only.value_arena_retained_bytes":                  "32768",
		"treedb.process.memtable_residency.queue.append_only.entry_backing_bytes":                       "7340032",
		"treedb.process.memtable_residency.queue.append_only.value_arena_retained_bytes":                "32768",
		"treedb.cache.append_only.mutable_entry_backing_bytes":                                          "55923200",
		"treedb.cache.append_only.mutable_value_arena_active_bytes":                                     "65536",
		"treedb.process.append_only.entry_pool_retained_bytes_estimate":                                 "27858800",
		"treedb.process.append_only.mem_lease_value_arena_retained_bytes":                               "131072",
		"treedb.cache.flush_apply.planning_ns_total":                                                    "101",
		"treedb.cache.leaf_log_lanes.append_lanes_used":                                                 "4",
		"treedb.cache.leaf_log_lanes.lane.01.append_calls_total":                                        "8",
		"treedb.cache.flush_span_run.source_point_ops_total":                                            "11",
		"treedb.cache.flush_span_run.planned_point_ops_total":                                           "10",
		"treedb.cache.flush_span_run.backend_chunks_total":                                              "4",
		"treedb.cache.checkpoint.total_ms":                                                              "1.250",
		"treedb.cache.checkpoint.cutover_last_ms":                                                       "0.500",
		"treedb.cache.checkpoint.stage.flush_all.total_ns":                                              "303",
		"treedb.flush_admission.policy":                                                                 "auto",
		"treedb.flush_admission.admitted":                                                               "true",
		"treedb.flush_admission.reason":                                                                 "auto_admitted_hardware_aware",
		"treedb.flush_admission.flush_apply_concurrency":                                                "8",
		"treedb.flush_admission.flush_apply_concurrency_defaulted":                                      "true",
		"treedb.flush_admission.gomaxprocs":                                                             "16",
		"treedb.flush_admission.physical_cores":                                                         "8",
		"treedb.flush_admission.flush_apply_span_native":                                                "true",
		"treedb.cache.flush_backlog_coalescing.admitted_runs_total":                                     "2",
		"treedb.cache.flush_backlog_coalescing.skip.reason.ops_budget_total":                            "1",
		"treedb.cache.queue_len":                                                                        "3",
		"treedb.cache.queue_backlog_bytes":                                                              "4096",
		"treedb.cache.vlog_retained_segments":                                                           "9",
		"treedb.cache.vlog_retained_bytes_estimate":                                                     "987654",
		"treedb.flush_apply.old_leaf_read_decode.leaf_log_node_loads_total":                             "7",
		"treedb.flush_apply.read_only_prepare.spans_total":                                              "3",
		"treedb.flush_apply.leaf_log_output.append_wait_ns_total":                                       "1234",
		"treedb.flush_apply.span_native.scheduler.worker_busy_ns_total":                                 "7000",
		"treedb.flush_apply.span_native.scheduler.worker_idle_ns_total":                                 "3000",
		"treedb.flush_apply.span_native.scheduler.ready_tasks_total":                                    "8",
		"treedb.flush_apply.span_native.scheduler.task_spans_per_task":                                  "6.000000",
		"treedb.flush_apply.publish_prepare.ns_total":                                                   "44",
		"treedb.flush_apply.publish_final_install.ns_total":                                             "55",
		"treedb.flush_apply.publish_total.ns_total":                                                     "99",
		"treedb.flush_apply.reducer_publish.ns_total":                                                   "99",
		"treedb.raw.span_native.candidate_ops_total":                                                    "12",
		"treedb.raw.span_native.route.point_put.used_ops_total":                                         "10",
		"treedb.raw.span_native.route.range_delete.fallback.reason.range_delete_barrier.ops_total":      "2",
		"treedb.raw.span_native.public.route.update_sync.fallback.reason.command_wal_barrier.ops_total": "1",
		"treedb.publish.ordered_root_delta_group.calls_total":                                           "19",
		"treedb.publish.ordered_root_delta_group.publish_prepare_ns_total":                              "66",
		"treedb.publish.ordered_root_delta_group.root_apply_read_only_prepare_spans_total":              "2",
		"treedb.publish.watermark.latency_p99_ms":                                                       "23",
		"treedb.collections.write_domain.indexed_flush.calls_total":                                     "29",
		"treedb.unrelated_stat_that_should_not_leave_the_helper":                                        "17",
	}
	got := Selected(stats)
	for _, key := range []string{
		"treedb.commit_seq",
		"treedb.applied_command_lsn",
		"treedb.command_wal.enabled",
		"treedb.command_wal.frames",
		"treedb.process.read_path.backend_tree.get_append_pointer_hits_total",
		"treedb.process.read_path.outer_leaf.cache.hits",
		"treedb.vlog.mmap_read.fallback_readat",
		"treedb.vlog.mmap_max_mapped_leaf_sealed_bytes",
		"treedb.vlog.decode_buffer_grow.read_append_decoded_payload.calls_total",
		"treedb.vlog.decode_scratch.small_pool.retained_bytes",
		"treedb.vlog.writer_append_buf.pool.retained_bytes",
		"treedb.vlog.grouped_frame_cache.retained_bytes",
		"treedb.vlog.grouped_frame_cache.allocated_slots",
		"treedb.cache.vlog_grouped_frame_cache.retained_bytes",
		"treedb.cache.vlog_grouped_frame_cache.allocated_slots",
		"treedb.process.memory.rss_bytes",
		"treedb.cache.vlog_mmap.max_mapped_leaf_sealed_segments",
		"treedb.cache.vlog_decode_buffer_grow.read_append_decoded_payload.calls_total",
		"treedb.cache.vlog_decode_scratch.small_pool.retained_bytes",
		"treedb.cache.vlog_writer_append_buf.pool.retained_bytes",
		"treedb.cache.vlog_auto.frames.block_lz4",
		"treedb.cache.vlog_auto.frames.block_zstd",
		"treedb.cache.vlog_write_mode.stored_ratio.block",
		"treedb.cache.vlog_payload_kind.frames.outer_leaf",
		"treedb.cache.vlog_payload_split.records.outer_leaf",
		"treedb.cache.vlog_outer_leaf_codec.frames.lz4",
		"treedb.cache.vlog_block.k.bucket.lz4.le_1",
		"treedb.cache.vlog_dict.frames_kept",
		"treedb.cache.vlog_autotune.observed_ratio",
		"treedb.cache.vlog_leaf_scan.write_mode.frames.block",
		"treedb.cache.memtable_residency.queue.append_only.entry_backing_bytes",
		"treedb.cache.memtable_residency.queue.append_only.value_arena_retained_bytes",
		"treedb.process.memtable_residency.queue.append_only.entry_backing_bytes",
		"treedb.process.memtable_residency.queue.append_only.value_arena_retained_bytes",
		"treedb.cache.append_only.mutable_entry_backing_bytes",
		"treedb.cache.append_only.mutable_value_arena_active_bytes",
		"treedb.process.append_only.entry_pool_retained_bytes_estimate",
		"treedb.process.append_only.mem_lease_value_arena_retained_bytes",
		"treedb.cache.flush_apply.planning_ns_total",
		"treedb.cache.leaf_log_lanes.append_lanes_used",
		"treedb.cache.leaf_log_lanes.lane.01.append_calls_total",
		"treedb.cache.flush_span_run.source_point_ops_total",
		"treedb.cache.flush_span_run.planned_point_ops_total",
		"treedb.cache.flush_span_run.backend_chunks_total",
		"treedb.cache.checkpoint.total_ms",
		"treedb.cache.checkpoint.cutover_last_ms",
		"treedb.cache.checkpoint.stage.flush_all.total_ns",
		"treedb.flush_admission.policy",
		"treedb.flush_admission.admitted",
		"treedb.flush_admission.reason",
		"treedb.flush_admission.flush_apply_concurrency",
		"treedb.flush_admission.flush_apply_concurrency_defaulted",
		"treedb.flush_admission.gomaxprocs",
		"treedb.flush_admission.physical_cores",
		"treedb.flush_admission.flush_apply_span_native",
		"treedb.cache.flush_backlog_coalescing.admitted_runs_total",
		"treedb.cache.flush_backlog_coalescing.skip.reason.ops_budget_total",
		"treedb.cache.queue_len",
		"treedb.cache.queue_backlog_bytes",
		"treedb.cache.vlog_retained_segments",
		"treedb.cache.vlog_retained_bytes_estimate",
		"treedb.flush_apply.old_leaf_read_decode.leaf_log_node_loads_total",
		"treedb.flush_apply.read_only_prepare.spans_total",
		"treedb.flush_apply.leaf_log_output.append_wait_ns_total",
		"treedb.flush_apply.span_native.scheduler.worker_busy_ns_total",
		"treedb.flush_apply.span_native.scheduler.worker_idle_ns_total",
		"treedb.flush_apply.span_native.scheduler.ready_tasks_total",
		"treedb.flush_apply.span_native.scheduler.task_spans_per_task",
		"treedb.flush_apply.publish_prepare.ns_total",
		"treedb.flush_apply.publish_final_install.ns_total",
		"treedb.flush_apply.publish_total.ns_total",
		"treedb.flush_apply.reducer_publish.ns_total",
		"treedb.raw.span_native.candidate_ops_total",
		"treedb.raw.span_native.route.point_put.used_ops_total",
		"treedb.raw.span_native.route.range_delete.fallback.reason.range_delete_barrier.ops_total",
		"treedb.raw.span_native.public.route.update_sync.fallback.reason.command_wal_barrier.ops_total",
		"treedb.publish.ordered_root_delta_group.calls_total",
		"treedb.publish.ordered_root_delta_group.publish_prepare_ns_total",
		"treedb.publish.ordered_root_delta_group.root_apply_read_only_prepare_spans_total",
		"treedb.publish.watermark.latency_p99_ms",
		"treedb.collections.write_domain.indexed_flush.calls_total",
	} {
		if got[key] == "" {
			t.Fatalf("Selected missing %s from %#v", key, got)
		}
	}
	if _, ok := got["treedb.unrelated_stat_that_should_not_leave_the_helper"]; ok {
		t.Fatalf("Selected kept unrelated stat: %#v", got)
	}
}

func TestSelectedDropsOrderedRootFreeFormTriageFields(t *testing.T) {
	const prefix = "treedb.publish.ordered_root_delta_group.span_native.triage.route.delta_batch_publish."
	stats := map[string]string{
		prefix + "context":            "full ordered-root iterator publish",
		prefix + "detail":             "warm ordered-root delta batches are the runtime candidate surface",
		prefix + "status":             "fallback",
		prefix + "candidate":          "true",
		prefix + "eligible":           "false",
		prefix + "used":               "false",
		prefix + "fallback_reason":    "span_native_not_implemented",
		prefix + "fallback_class":     "route",
		prefix + "admission_policy":   "auto",
		prefix + "admission_admitted": "true",
		prefix + "admission_reason":   "auto_admitted_hardware_aware",
		prefix + "selected_workers":   "6",
	}

	got := Selected(stats)
	for _, key := range []string{prefix + "context", prefix + "detail"} {
		if _, ok := got[key]; ok {
			t.Fatalf("Selected kept free-form triage field %s in %#v", key, got)
		}
	}
	for _, key := range []string{
		prefix + "status",
		prefix + "candidate",
		prefix + "eligible",
		prefix + "used",
		prefix + "fallback_reason",
		prefix + "fallback_class",
		prefix + "admission_policy",
		prefix + "admission_admitted",
		prefix + "admission_reason",
		prefix + "selected_workers",
	} {
		if got[key] == "" {
			t.Fatalf("Selected dropped token-safe triage field %s from %#v", key, got)
		}
	}
}
