#!/usr/bin/env bash
set -euo pipefail

ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
cd "$ROOT"

TMP_BASE="${TMPDIR:-/tmp}"
TMP_BASE="${TMP_BASE%/}"
OUT_DIR="${OUT_DIR:-$(mktemp -d "$TMP_BASE/treedb_fast_client_matrix_XXXXXX")}" 

# Standard client-shape matrix used by issue #2335. Defaults match the profiled
# gateway-shaped workload closely enough for product evidence; override DOCS_LIST
# and TIMEOUT for smoke runs.
DOCS_LIST="${DOCS_LIST:-200000}"
INDEXES_LIST="${INDEXES_LIST:-2}"
BATCH_SIZE="${BATCH_SIZE:-1000}"
INSERT_PRODUCERS="${INSERT_PRODUCERS:-16}"
CONCURRENT_READERS="${CONCURRENT_READERS:-16}"
CONCURRENT_READ_KINDS="${CONCURRENT_READ_KINDS:-id,email}"
CONCURRENT_READS="${CONCURRENT_READS:-100000}"
READS="${READS:-0}"
RANGE_READS="${RANGE_READS:-0}"
UPDATES="${UPDATES:-0}"
DELETES="${DELETES:-0}"
DOCUMENT_SHAPE="${DOCUMENT_SHAPE:-gateway}"
POINT_READ_PROJECTION="${POINT_READ_PROJECTION:-full}"
PREBUILD_DOCUMENTS="${PREBUILD_DOCUMENTS:-true}"
TREEDB_PROFILE="${TREEDB_PROFILE:-command_wal_relaxed}"
TREEDB_DOCUMENT_FORMATS="${TREEDB_DOCUMENT_FORMATS:-bson}"
TREEDB_MAINTENANCE="${TREEDB_MAINTENANCE:-none}"
TREEDB_READ_STATE="${TREEDB_READ_STATE:-settled}"
TREEDB_CLIENT_MODES="${TREEDB_CLIENT_MODES:-driver driver-command driver-command-raw raw-wire-tcp native-wire-tcp direct}"
MONGO_CLIENT_MODES="${MONGO_CLIENT_MODES:-driver driver-command driver-command-raw driver-unack}"
MONGO_MODE="${MONGO_MODE:-docker}"
MONGO_URI="${MONGO_URI:-mongodb://127.0.0.1:27017}"
MONGO_IMAGE="${MONGO_IMAGE:-mongo:8}"
MONGO_MAX_POOL_SIZE="${MONGO_MAX_POOL_SIZE:-16}"
MONGO_MIN_POOL_SIZE="${MONGO_MIN_POOL_SIZE:-0}"
MONGO_MAX_CONNECTING="${MONGO_MAX_CONNECTING:-16}"
TIMEOUT="${TIMEOUT:-30m}"
PROFILE_TREEDB="${PROFILE_TREEDB:-false}"
TITLE="${TITLE:-TreeDB fast Mongo/native client-shape matrix}"

export OUT_DIR DOCS_LIST INDEXES_LIST BATCH_SIZE INSERT_PRODUCERS \
  CONCURRENT_READERS CONCURRENT_READ_KINDS CONCURRENT_READS READS RANGE_READS \
  UPDATES DELETES DOCUMENT_SHAPE POINT_READ_PROJECTION PREBUILD_DOCUMENTS \
  TREEDB_PROFILE TREEDB_DOCUMENT_FORMATS TREEDB_MAINTENANCE TREEDB_READ_STATE \
  TREEDB_CLIENT_MODES MONGO_CLIENT_MODES MONGO_MODE MONGO_URI MONGO_IMAGE \
  MONGO_MAX_POOL_SIZE MONGO_MIN_POOL_SIZE MONGO_MAX_CONNECTING TIMEOUT \
  PROFILE_TREEDB TITLE

scripts/mongo_gateway_compare.sh

cat >"$OUT_DIR/fast_client_matrix_context.md" <<EOF
# Fast Client Matrix Context

This bundle was produced by \`scripts/mongo_gateway_fast_client_matrix.sh\`.

Important interpretation boundaries:

- Client modes are not interchangeable. Compare MongoDB and TreeDB only where the
  client mode and acknowledgement semantics match.
- \`driver-command-raw\` and direct paths avoid some driver decode work, but raw
  command/document construction may still be benchmark-side cost unless
  \`PREBUILD_DOCUMENTS=true\` is in effect.
- TreeDB \`load_insert_many\` rows in settled read-state runs include foreground
  insert timing plus settled drain/flush time. The raw JSON phase emits
  \`treedb_metrics.foreground_duration_ms\`,
  \`treedb_metrics.settled_drain_duration_ms\`, and
  \`treedb_metrics.settled_drain_included\` to make that boundary explicit.
- \`direct\` is a TreeDB storage/collection ceiling, not a Mongo protocol row.
- \`raw-wire-tcp\` and \`native-wire-tcp\` isolate official-driver overhead from
  gateway/native protocol and TreeDB storage/index costs.

Primary files:

- \`README.md\`: bundle index generated by \`mongo_gateway_compare.sh\`.
- \`summary.tsv\`: flattened comparison rows.
- \`report.md\`: human-readable TreeDB-vs-MongoDB report.
- \`raw/*.json\`: unmodified \`mongo_gateway_bench -format json\` output with
  per-phase metadata and TreeDB phase metrics.
EOF

printf 'fast client matrix bundle: %s\n' "$OUT_DIR"
